### ISSUE TITLE
Class Tuesday 3/31

### ISSUE THREAD

**Issue by johnnybenson** [IDMNYU/DM2193SP2015#10]
## Reminder: Finished Midterms are due, pushed up to Github before class.
- PDF and / or HTML Document
- Fully finished designs, wireframes, etc. See Midterm README.
- Really try to kick butt on these please!
## Homework: Codecademy Javascript
- http://www.codecademy.com
- http://www.codecademy.com/tracks/javascript
- See how far you can get with the HTML & CSS one as a refresher!
## Class won't be in room 811

We are holding class at Tumblr on Tuesday 3/31
### Address https://goo.gl/maps/KfYvu

35 E. 21st Street, 10th Floor
New York NY 10010

[Email me](mailto:jdb12@nyu.edu?subject=[Class on 3/31]) ahead of time if you are not going to make it.

**Comment by johnnybenson** [comment]
It's about 25 minutes from TumblrHQ to Metrotech including walking time.

#### Subway Lines
- F from Jay St. to 23rd
- Q from Dekalb to Union Sq
- 4/5 from Borough Hall to Union Sq -- could transfer to the 6 and get off at 23rd.

**Comment by ziros94** [comment]
Where is everyone, Alan and I are here

On Monday, March 30, 2015, Johnny Benson notifications@github.com wrote:

> It's about 25 minutes from TumblrHQ to Metrotech including walking time.
> Subway Lines
> - F from Jay St. to 23rd
> - Q from Dekalb to Union Sq
> - 4/5 from Borough Hall to Union Sq -- could transfer to the 6 and get
>   off at 23rd.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IDMNYU/DM2193SP2015/issues/10#issuecomment-87880546.

## 

Sincerely,

Alvi Kabir

**Comment by Azerafa** [comment]
It's on 21st by park right? Call me 2487982362

**Comment by ziros94** [comment]
We're freeloading

On Tuesday, March 31, 2015, Alvi Kabir alvi.kab@nyu.edu wrote:

> Where is everyone, Alan and I are here
> 
> On Monday, March 30, 2015, Johnny Benson <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> 
> > It's about 25 minutes from TumblrHQ to Metrotech including walking time.
> > Subway Lines
> > - F from Jay St. to 23rd
> > - Q from Dekalb to Union Sq
> > - 4/5 from Borough Hall to Union Sq -- could transfer to the 6 and
> >   get off at 23rd.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/IDMNYU/DM2193SP2015/issues/10#issuecomment-87880546.
> 
> ## 
> 
> Sincerely,
> 
> Alvi Kabir

## 

Sincerely,

Alvi Kabir

**Comment by ziros94** [comment]
The building number is 35

On Tuesday, March 31, 2015, Alvi Kabir alvi.kab@nyu.edu wrote:

> We're freeloading
> 
> On Tuesday, March 31, 2015, Alvi Kabir <alvi.kab@nyu.edu
> <javascript:_e(%7B%7D,'cvml','alvi.kab@nyu.edu');>> wrote:
> 
> > Where is everyone, Alan and I are here
> > 
> > On Monday, March 30, 2015, Johnny Benson notifications@github.com
> > wrote:
> > 
> > > It's about 25 minutes from TumblrHQ to Metrotech including walking time.
> > > Subway Lines
> > > - F from Jay St. to 23rd
> > > - Q from Dekalb to Union Sq
> > > - 4/5 from Borough Hall to Union Sq -- could transfer to the 6 and
> > >   get off at 23rd.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/IDMNYU/DM2193SP2015/issues/10#issuecomment-87880546
> > > .
> > 
> > ## 
> > 
> > Sincerely,
> > 
> > Alvi Kabir
> 
> ## 
> 
> Sincerely,
> 
> Alvi Kabir

## 

Sincerely,

Alvi Kabir

**Comment by itsjohnward** [comment]
I'm lost. 35 21st street seems to be a salon.

**Comment by ziros94** [comment]
Uh you sure you're on the right street

On Tuesday, March 31, 2015, John Ward notifications@github.com wrote:

> I'm lost. 35 21st street seems to be a salon.
> 
> On Tue, Mar 31, 2015 at 7:27 PM, Alvi Kabir <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > The building number is 35
> > On Tuesday, March 31, 2015, Alvi Kabir <alvi.kab@nyu.edu
> > <javascript:_e(%7B%7D,'cvml','alvi.kab@nyu.edu');>> wrote:
> > 
> > > We're freeloading
> > > 
> > > On Tuesday, March 31, 2015, Alvi Kabir <alvi.kab@nyu.edu
> > > <javascript:_e(%7B%7D,'cvml','alvi.kab@nyu.edu');>
> > > <javascript:_e(%7B%7D,'cvml','alvi.kab@nyu.edu
> > > <javascript:_e(%7B%7D,'cvml','alvi.kab@nyu.edu');>');>> wrote:
> > > 
> > > > Where is everyone, Alan and I are here
> > > > 
> > > > On Monday, March 30, 2015, Johnny Benson <notifications@github.com
> > > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > > > wrote:
> > > > 
> > > > > It's about 25 minutes from TumblrHQ to Metrotech including walking
> > > > > time.
> > > > > Subway Lines
> > > > > - F from Jay St. to 23rd
> > > > > - Q from Dekalb to Union Sq
> > > > > - 4/5 from Borough Hall to Union Sq -- could transfer to the 6 and
> > > > >   get off at 23rd.
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> > > > > https://github.com/IDMNYU/DM2193SP2015/issues/10#issuecomment-87880546>
> > > > > .
> > > > 
> > > > ## 
> > > > 
> > > > Sincerely,
> > > > 
> > > > Alvi Kabir
> > > 
> > > ## 
> > > 
> > > Sincerely,
> > > 
> > > Alvi Kabir
> > > 
> > > ## 
> > > 
> > > Sincerely,
> > > 
> > > ## Alvi Kabir
> > > 
> > > Reply to this email directly or view it on GitHub:
> > > https://github.com/IDMNYU/DM2193SP2015/issues/10#issuecomment-88282053
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IDMNYU/DM2193SP2015/issues/10#issuecomment-88282777.

## 

Sincerely,

Alvi Kabir

**Comment by itsjohnward** [comment]
Think I was at 35 instead of 35 East or whatever. Following google maps now. 6 minutes away apparently.

**Comment by therealshah** [comment]
For some reason I thought it was on 34 st lololol I'm on 34 st :/

**Comment by johnnybenson** [comment]
you are terrible!
