### ISSUE TITLE
Did everyone email me their 1 question from last week?

### ISSUE THREAD

**Issue by johnnybenson** [IDMNYU/DM2193SP2015#2]
I've got six unread emails. I'm looking for 10 more by class time tomorrow!

**Comment by ziros94** [comment]
What's a pseudo selector and why are they used?

On Monday, March 2, 2015, Johnny Benson notifications@github.com wrote:

> I've got six unread emails. I'm looking for 10 more by class time tomorrow!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/IDMNYU/DM2193SP2015/issues/2.

## 

Sincerely,

Alvi Kabir

**Comment by therealshah** [comment]
For the blue box we created, how would we get it to change a different
color when we click on it or hover over it ?

Thanks
Shahzaib

**Comment by sds558** [comment]
How would you proficiently create a menu bar? What would the code look like?
