### ISSUE TITLE
Midterm Reminder

### ISSUE THREAD

**Issue by johnnybenson** [IDMNYU/DM2193SP2015#7]
Just a reminder for all of us coming back from spring break.

Come to class Tuesday prepared to present your Midterm work. 

You are pitching the class your Craigslist redesign. Explain your reasoning and show off wireframes and designs.

Email me with questions or ask them right here in the Github issue.

Thanks!

**Comment by Jun500** [comment]
I just wanted to ask how exactly we are presenting the Midterm. Are we
suppose to at least get it on a section on Github or more so our site and
present it from there?

**Comment by johnnybenson** [comment]
That's up to you. What ever you think helps.

paragraph or two about your idea
three wireframes
three designs

committed to github

if you want to make a pdf or a keynote or a google presentation, feel free

commit the link to your learning log on github

you get three minutes to pitch!

goodluck :)

**Comment by gitHubCal** [comment]
Is the design part creating an HTML/CSS document?

**Comment by johnnybenson** [comment]
There's no coding in the midterm at all! Can elaborate more in class on Tues

**Comment by gitHubCal** [comment]
Would the design be drawing flowcharts or something similar?

**Comment by johnnybenson** [comment]
Designs should look as close to the real thing as possible.

You should produce wireframes as well, but flow charts, or user flows, or any other diagrams you find helpful in telling your story is totally OK.

You will have more time to revise and iterate on these after Tuesday's class too.

**Comment by dmsirota** [comment]
Professor,

Do the wireframes need to be done on the computer? Aka, are hand drawings
not acceptable (even if drawn on graph paper with some epic neatness)?

**Comment by johnnybenson** [comment]
follow your heart, take a picture of your graph paper and make a pdf!

it just has to end up on your github

**Comment by johnnybenson** [comment]
Reminder: You were supposed to fill out self-assessments yesterday! There's a mailto: link on the midterm README in the repo.

**Comment by therealshah** [comment]
Hi professor.
             I forgot to do the evaluation. I tried to click the link but
it doesn't work. Sorry.

Thanks
 Shahzaib
